
service:
  name: notification-service

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 128
  iamRoleStatements:
    - ${file(iam/send-email-iam.yml):SendEmailIAM}

functions:
  send-email:
    handler: dist/handlers/send-email.handler